-- Treatment catalog: real, stored, extensible treatment records.
--
-- Run this once against the project's Supabase database (SQL editor or
-- `supabase db execute` / CLI migration apply). The application code
-- assumes this schema exists; it does not create it.
--
-- To add a treatment later, insert a new row — no code or deploy needed:
--   insert into treatments (name, display_order) values ('Teeth Whitening', 9);

create table if not exists treatments (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_active boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table treatments enable row level security;

create policy "Authenticated users can read treatments"
  on treatments
  for select
  to authenticated
  using (true);

-- Initial seed / catalog. Not the clinic's complete offering — additional
-- treatments can be inserted at any time without touching this file again.
insert into treatments (name, display_order) values
  ('Consultation', 1),
  ('Dental Cleaning', 2),
  ('Dental Filling', 3),
  ('Root Canal Treatment', 4),
  ('Tooth Extraction', 5),
  ('Crown', 6),
  ('Invisalign', 7),
  ('Other', 8)
on conflict (name) do nothing;
